### PR TITLE
fixes #9

### LINKED ISSUE #9: pooled resource is not being returned to pool
the current WorkerImpl is never returning Jedis ressources to the pool. Like this the pool is exhausted insanly fast (with default configuration) or has to be tuned alot to handle all those connection (local test with 4 Workers and 1000 maxTotal connections resultet in pool exhaustion in under one minute)

### PR DESCRIPTION
**Pull request by peh**
this should fix #9 

I groovyfied the WorkerImpl as i had to touch a lot of code anyways.
As soon as https://github.com/gresrun/jesque/issues/109 we should consider getting rid of that "custom" WorkerImpl completly and use the original WorkerPoolImpl.

I also cleaned up some stuff that was never used in the custom WorkerImpl

### CODE REVIEW

**Comment by ctoestreich** [comment]
I was going to do this today as we had to switch to a Jewish scan vs key and I realized that the connection needs an explicit close.  Will review asap.

**Comment by peh** [comment]
sorry wrong button :)

**Comment by ctoestreich** [comment]
We really need more tests around this thing.... releasing now 1.1.9.

**Comment by ctoestreich** [comment]
#thanks

**Pull request merged**
